### ISSUE TITLE
expectUrl Issue

### ISSUE THREAD

**Issue by lwalik** [Lowgular/testgular#1]
- **The title of the video in the course**: 'Router Basic'
- **Time: approx**. 3:45
- **Testgular version**: ^0.0.69
- **Description**: When I pass '/' to the expectUrl method it doesn't see the appUrl it just sees exactly what I pass it and then the url doesn't match anyway because the string I passed sees it like this: "/^\s*\/\s*$/"
- **Test example**: 
```
it('hello', APP_CONFIG, async (app: App) => {
	// Given
	const router = app.inject(Router);
	await router.navigateAndWait('/');
	// Then
	await router.expectUrl('/');
});
```

**Comment by gradzio** [comment]
Weszly zmiany w nowej wersji
