### ISSUE TITLE
Submit by pressing enter

### ISSUE THREAD

**Issue by lwalik** [Lowgular/testgular#10]
Film: Submit -> Submit by pressing enter
Opis:
Metodę tę wykonujemy na SubmitControl, a czy są przypadki, że są formy, które nie mają submit button tylko właśnie jedyna opcja to zatwierdzenie enterem? Co w takim przypadku, jest to możliwe do zrobienia i czy takie coś się stosuje?

**Comment by gradzio** [comment]
no teoretycznie wszystko jest mozliwe, tutaj glownie chodzi oto ze wcisniecie enter powoduje submit format (default dla browsera) ale nie musi to byc case. Generalnie uzywa sie pressEnter zeby sprawdzic czy developer to wszystko podpial, troche takie sprawdzenie dobrych praktyk UX
