### ISSUE TITLE
SelectOption with string[]

### ISSUE THREAD

**Issue by lwalik** [Lowgular/testgular#11]
Film: Select -> Select Basic
Opis:
Metoda selectOption jest pokazane, że może przyjąć string[]. W jaki sposób można tego użyć. Jaki jest przykład użycia kiedy tam przekażemy string[]?

**Comment by gradzio** [comment]
wsumie jest to do usuniecia bo jest inny form control do tego

**Comment by gradzio** [comment]
Resolved in v0.0.111
