### ISSUE TITLE
SelectOption method

### ISSUE THREAD

**Issue by lwalik** [Lowgular/testgular#12]
Film: Select -> Select Basic
Opis:
Istnieje metoda selectOptionByValue, selectOptionByLabel, to po co nam jeszcze 3 metoda selectOption?
Kiedy w praktyce może nam się to przydać?

**Comment by gradzio** [comment]
dobre pytanie, selectOption powoduje fallback, jest takim jakby ulatwieniem, on najpierw wchodzi w value a potem w label - pytanie czy to jest potrzebne?

**Comment by lwalik** [comment]
selectOptionBy... jest bardziej konkretne chyba skoro selectOption tak na prawdę docelowo robi to samo, jeśli dobrze zrozumiałem
