### ISSUE TITLE
File path

### ISSUE THREAD

**Issue by lwalik** [Lowgular/testgular#13]
Film: File -> File Basic
Opis:
Pokazujesz przypadek sprawdzania ścieżki i do sprawdzenia najpierw wypisujesz za pomocą "getValue", kopiujesz i ją sprawdzasz, a co jeśli getValue zwróciłoby błędą ścieżkę bo ktoś źle jakoś ogarnął inputa np.?

Czy to było pokazanie jak to wygląda i w praktyce w Playwirght zawsze to będzie `C:\fakepath\<fileName_with_extension>`?

**Comment by gradzio** [comment]
nie rozumiem, w filmiku mam expectValue a nie getValue - nie wiem oco pytasz gdzie dokladnie to jest?

**Comment by lwalik** [comment]
Tam do expect wkleiłeś scieżkę którą otrzymałeś po tym jak console.log zrobiłeś na ścieżkę
