### ISSUE TITLE
Select by Value

### ISSUE THREAD

**Issue by lwalik** [Lowgular/testgular#14]
Film: Radio -> Radio Group Select By Value i inne gdzie pobieramy element po Value
Opis:
Kiedy ma zastosowanie, że pobieramy element po Value i potem robimy expectValue. Czy skoro udało nam się pobrać taki element to nie jest to oczywiste że expectValue będzie takie samo?

**Comment by gradzio** [comment]
ok mamy 3 rzeczy. Kazdy test sklada sie z Given When Then i mozna zrobic tak:
Given -> pobrac element po value np mozesz uzyc  cssSelector([value=""]) ale to sluzy do pobierania elementu
When -> getValue (tutaj nie pobieramy elementu, tylko aktualna wartosc elementu)
Then -> expectValue to jest najlepsze bo odrazu rzuci errorem i zatrzyma test

Podsumowujac mozna to zrobic na kilka spososbow ale semantycznie to sa 3 rozne rzeczy, maja tez inne timeouty i wydluzaja niepotrzebnie test. Dlatego lepiej jakbys uzywal expectValue
