### ISSUE TITLE
ExpectUrl after redirect

### ISSUE THREAD

**Issue by lwalik** [Lowgular/testgular#16]
Materiał: Exercises -> Button Exercise 1
Opis:
Nie wiem czemu jak biorę expectUrl to obojętnie co tam nie podam to to ignoruje i mam taki wynik: 
			` Error: expect(received).toMatch(expected)`

`Expected pattern: /^https:\/\/storage\.googleapis\.com\/testgular-course\/atoms\/button-showcases/i`
`Received string:  "https://www.google.com/"`

Jeśli użyję expectAndWaitForUrl to też test nie przechodzi pomimo, że jak użyję z flagą --headed to widzę, że przenosi na google.com
 Tak jakby był bug, który nie sprawdza tego co mu się przekazuje tylko base url

**Comment by gradzio** [comment]
w Twoim zadaniu  brakowalo Ci slasha na koncu
