### ISSUE TITLE
Select Input Element

### ISSUE THREAD

**Issue by lwalik** [Lowgular/testgular#17]
Materiał: Exercises -> Input Exercise
Opis:
W materiałach mówiłeś, że id nie jest dobrą opcją, że lepszą jest Label bo jest to coś biznesowego. Lecz w tych zadaniach nie dało się po label bo na page'u /b.html nie ma label, więc jaka najlepsza opcja do pobrania takiego elementu?

**Comment by gradzio** [comment]
najlepsza jest label / placeholder ale jak sie nie da to trzeba po testid lub css i wtedy lepiej korzystac z id niz classy cssowej
