### ISSUE TITLE
Issue: Radio Exercise Description

### ISSUE THREAD

**Issue by lwalik** [Lowgular/testgular#19]
Materiał: Exercises -> Radio Exercise
Opis:
W App url jest podany na końcu '/', a w inynch zadaniach nie. Jest to problemem, ponieważ w page'ach też na początku jest podany '/' więc jak użyjemy tak jak jest podane w zadaniu to będzie błąd, ponieważ będziemy mieli '//' (2 x /)

Czy to błąd?

**Comment by gradzio** [comment]
wsumie mozna sie pomylilc, podmienilem to
