### ISSUE TITLE
Path for path.join method

### ISSUE THREAD

**Issue by lwalik** [Lowgular/testgular#20]
Przy zadaniach z file trzeba użyć path tego standardowego. Standardowo taki import jest niemożliwy i trzeba zmienić opcję w tsconfig.json. Brakowało mi tego w materiałach aby to było pokazane.

**Comment by gradzio** [comment]
spoko, wsumie importow nie widac na filmiku, dodam taki filmik

**Comment by gradzio** [comment]
dodane do filmiki
