### ISSUE TITLE
Additional Matchers

### ISSUE THREAD

**Issue by lwalik** [Lowgular/testgular#23]
Brakuje mi więcej Matcherów czy czegoś takiego, abym mógł bardziej ręcznie także manipulować, jak np. Matcher do tego że tylko część stringa chcę aby się zgadzała. 

Działa z metodą mapToUnboundedRegexp ale trochę nie wiem co ona robi.

**Comment by gradzio** [comment]
mapToUnboundedRegexp tak naprawde powoduje uzycie stringa jako regexp i dodaje flag global i opcjonalnie case insensitive
