### ISSUE TITLE
Matcher 'mustContainWords'

### ISSUE THREAD

**Issue by Ramotka** [Lowgular/testgular#24]
Sometimes in a string (label/text etc.) apart from some key words that always need to be present there are other irrelevant words that don't matter for my test. Example: "Terms and Conditions", "     terms & conditions    ", "Accept terms and all conditions", "Conditions & terms" etc. What I really care about here are two words: 'terms' and 'conditions'. I would like to select the element by just providing my key words: all spaces, other words, case or the order of my key words are not important.

I need something like that:

StringMatcher.mustContainWords(['terms', 'conditions'])

Regex could be similar to this (but it's still not perfect): /\.*?\bterms\b.*?\bconditions\b.*?/i

**Comment by gradzio** [comment]
dodano w wersji 0.0.116
