### ISSUE TITLE
Literówka w metodzie selectByIndicies

### ISSUE THREAD

**Issue by Ramotka** [Lowgular/testgular#33]
Nieregularna liczba mnoga od slowa index to **indices** a nie indicies wiec powinno byc selectByIndices :) 
Co ciekawe akurat dla slowa index istnieja dwie poprawne formy liczby mnogiej, nie tylko ta łacińska, więc mozna nawet dac selectByIndexes

![image](https://github.com/Lowgular/testgular/assets/100229674/0e48842a-30b8-4b31-bd2c-65416559dbe0)
![image](https://github.com/Lowgular/testgular/assets/100229674/6942c1c1-123b-4182-ad8d-3ce5eb84454f)

**Comment by gradzio** [comment]
fixed in 0.0.121
