### ISSUE TITLE
Incomprehensible operation of exactCaseInsensitiveRegexp

### ISSUE THREAD

**Issue by lwalik** [Lowgular/testgular#4]
Video: Image Element -> Expect Content with Matcher
Exercise: Exercises -> Button Exercise 1

Description: 
For "Koala Image" using this method works correctly, but why doesn't it work for "Donkey Image"? You said it is because we used this method but could you describe it more?

exactCaseInsensitiveRegexp method helps when there are uppercase and lowercase letters but does not help when there are spaces at the beginning or end. How can this be combined to work for both cases without manually using RegExp?

**Comment by gradzio** [comment]
stworzyc jakis helper dla: case insensitive + spaces

**Comment by gradzio** [comment]
dodalem do exactCaseInsensitiveRegexp 2 opcjonalne parametry (default false) mayStartWithSpace i mayEndWithSpace, teraz mozna uzywac ich jak chce sie spacje przed i/lub po
