### ISSUE TITLE
Button Role Selector

### ISSUE THREAD

**Issue by lwalik** [Lowgular/testgular#6]
Video: Button -> Button Role Selector
Description:
The video shows the use of the buttonRoleSelector method, where you pass text (Content). How is this then different from the TextSelector method and is the buttonRoleSelector method needed? Does it work to find an element with the selector "<button>" or another selector that has the attribute "role="button"? This is not clear to me.

**Comment by gradzio** [comment]
https://playwright.dev/docs/locators#locate-by-role
