### ISSUE TITLE
Using the waitForTimeout method

### ISSUE THREAD

**Issue by lwalik** [Lowgular/testgular#7]
Video: Button -> Expect Visible Modal after Click
Description: 
In the video, the waitForTimeout method was used. You said it's a good idea to give a longer timeout there than the animation, but should the person who writes the tests have information about how long the animation will last or does he have to shoot around a bit? You said that in the future you will show a better solution for this, but how do you currently do it?

**Comment by gradzio** [comment]
currently you need to use waitForTimeout in fututre there will learn other tricks that you can use in order to by pass the timeout :)
