### ISSUE TITLE
Checkbox Check

### ISSUE THREAD

**Issue by lwalik** [Lowgular/testgular#8]
Film: Checkbox -> Check Uncheck and Click
Opis:
Na samym końcu filmu pokazałeś przypadek, gdzie dwa razy wykonałeś metodę "check" i powiedziałeś, że oczekiwałbyś, że nie przejdzie a przeszedł i zakończyłeś filmik w takim momencie. Jak to w końcu powinno być. Sprawdziłem i nie istnieje specjalna metoda Uncheck.

**Comment by gradzio** [comment]
dzieki, filmik poprawiony
