### ISSUE TITLE
Label Selector for Checkbox

### ISSUE THREAD

**Issue by lwalik** [Lowgular/testgular#9]
Film: Checkbox -> Label Selector
Opis: 
Tam jest, że pobieramy CheckboxControl po labelSelector i klikamy, ale czy to w praktyce pobiera checkbox i metoda "check" jest tak jakbyśmy klikali w checkbox czy jakbyśmy klikali w Label? Bo jak mieć pewność, że działa zaznaczenie checkboxa poprzez kliknięcie w label?

**Comment by gradzio** [comment]
klikamy w checkbox ale musi labelka byc polaczona z checkboxem albo checkbox musi w niej byc albo uzyc for + id atribute
